# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY gateway ./gateway
COPY services ./services
COPY pkg ./pkg
COPY go.work ./

WORKDIR /app/gateway
RUN go work sync
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gateway .

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/gateway/gateway .

EXPOSE 80

CMD ["./gateway"]
