# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.work ./
COPY services/user-service ./services/user-service
COPY services/order-service ./services/order-service
COPY gateway ./gateway
COPY pkg ./pkg

WORKDIR /app/gateway
RUN go mod tidy &&  CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gateway .

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/gateway/gateway .

EXPOSE 80

CMD ["./gateway"]
