# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY gateway ./gateway
COPY services ./services
COPY pkg ./pkg
COPY go.work ./
RUN go work sync

WORKDIR /app/services/user-service
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o user-service .

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/services/user-service/user-service .

EXPOSE 8080

CMD ["./user-service"]
